name: Playwright Tests
on:
  pull_request:
    branches:
      - master
  issue_comment:
    types: [edited]

jobs:
  test:
    timeout-minutes: 1
    runs-on: ubuntu-latest
    steps:
      - name: Capture Vercel preview URL
        id: vercel_preview_url
        uses: aaron-binary/vercel-preview-url-action@v0.0.3
