name: Playwright Tests
on:
  push:
    branches:
      - master
  issue_comment:
    types: [edited]

jobs:
  test:
    timeout-minutes: 5
    runs-on: ubuntu-latest
    steps:
      - name: Capture Vercel preview URL
        id: vercel_preview_url
        uses: aaron-binary/vercel-preview-url-action@v0.0.3
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Test output
        run: echo "URL is ${{ URL }} or ${{ steps.vercel_preview_url.outputs.vercel_preview_url }}"
