name: Playwright Tests
on:
  issue_comment:
    types: [edited]

jobs:
  test:
    timeout-minutes: 1
    runs-on: ubuntu-latest
    steps:
      - name: Capture Vercel preview URL
        id: vercel_preview_url
        uses: aaron-binary/vercel-preview-url-action@v0.0.3
      - name: Prepare testing env
        uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: "14"
      - run: npm ci
      - run: npx playwright install --with-deps
      - name: Run tests
        run: npm test:e2e
        env:
          PLAYWRIGHT_TEST_BASE_URL: ${{ steps.vercel_preview_url.outputs.vercel_preview_url }}
